spring.application.name=demo
spring.datasource.url=jdbc:postgresql://student.c9i0qik0u7ss.us-west-2.rds.amazonaws.com/student
spring.datasource.username=varun
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always